#!/bin/bash
#
# About:
#
#   Program for initial Debian configuration.
#
# Usage:
#
#   bash <(curl -s https://raw.githubusercontent.com/cicerops/autopilot/main/debian-bootstrap.sh)
#
# License:
#
#   GNU General Public License, version 3
#
# References:
#
set +ex


# Configuration
PACKAGES=""
PACKAGES="${PACKAGES} htop iotop iftop lsof tcpdump ngrep net-tools dnsutils whois wget curl httpie"
PACKAGES="${PACKAGES} tmux silversearcher-ag bzip2 ncdu nano"

PROFILE_FILE=/etc/profile.d/cicerops.sh


function install_packages {
  apt-get update
  apt-get install --yes ${PACKAGES}
}


function configure_profile {
  cat << EOF > "${PROFILE_FILE}"
#
# !!! ATTENTION !!!
#
# Automatically generated by cicerops autopilot. Please do not modify.
#

# Environment variable adjustments.
export HISTSIZE=999999
export HISTFILESIZE=999999

# Program aliases.
alias l='ls -alF --color'
EOF
}



function main {
  install_packages
  configure_profile
}


main
